#https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=
format_code_in_doc_comments = true
format_strings              = true
wrap_comments               = true
format_macro_bodies         = true
format_macro_matchers       = true
imports_granularity         = "Item"
comment_width               = 100
max_width                   = 120
